DATASET: !!python/object/new:easydict.EasyDict
  dictitems:
    NUM_JOINTS: 20
    TRAIN_DATA_PATH: &id001
    - /home/jysuh/PycharmProjects/coord_embedding/dataset/coord_valid.json
    - /home/jysuh/PycharmProjects/coord_embedding/dataset/coord_data_valid.json
    VALID_DATA_PATH: /home/jysuh/PycharmProjects/coord_embedding/dataset/coord_valid.json
  state:
    NUM_JOINTS: 20
    TRAIN_DATA_PATH: *id001
    VALID_DATA_PATH: /home/jysuh/PycharmProjects/coord_embedding/dataset/coord_valid.json
FILE_NAME: '[CosFace]: activation:Mish only_metric:True total epoch:1000 warmup:True
  max_iter:1000 perplexity:40'
GEN_BERT_DATASET: true
GPUS: '0'
MODE: TEST
PRETRAINED: true
PRETRAINED_PATH: '/home/jysuh/PycharmProjects/coord_embedding/checkpoint/[CosFace]:
  activation:Mish only_metric:True total epoch:1000 warmup:True max_iter:1000 perplexity:40.pth.tar'
PRINT_FREQ: 50
SEED: 8438
TRAIN: !!python/object/new:easydict.EasyDict
  dictitems:
    ACT: Mish
    ACT_LIST: &id003
    - ReLU
    - GELU
    BATCH_SIZE: 1
    EMB_DIM: &id004
    - 512
    EPOCH: 1000
    LOSS: CosFace
    LOSSES: &id005
    - CosFace
    - ArcFace
    LR: 0.0005
    M_RANGE: &id006
    - !!python/object/apply:numpy.core.multiarray.scalar
      - &id002 !!python/object/apply:numpy.dtype
        args:
        - f8
        - false
        - true
        state: !!python/tuple
        - 3
        - <
        - null
        - null
        - null
        - -1
        - -1
        - 0
      - !!binary |
        mpmZmZmZqT8=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        mpmZmZmZuT8=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        MzMzMzMzwz8=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        mpmZmZmZyT8=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        AAAAAAAA0D8=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        MzMzMzMz0z8=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        ZmZmZmZm1j8=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        mpmZmZmZ2T8=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        zczMzMzM3D8=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        AAAAAAAA4D8=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        mpmZmZmZ4T8=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        MzMzMzMz4z8=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        zczMzMzM5D8=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        ZmZmZmZm5j8=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        AAAAAAAA6D8=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        mpmZmZmZ6T8=
    NUM_SAMPLE: 2500
    ONLY_METRIC_LEARN: true
    SHUFFLE: true
    S_RANGE: &id007
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        AAAAAAAA8D8=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        AAAAAAAAAEA=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        AAAAAAAACEA=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        AAAAAAAAEEA=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        AAAAAAAAFEA=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        AAAAAAAAGEA=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        AAAAAAAAHEA=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        AAAAAAAAIEA=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        AAAAAAAAIkA=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        AAAAAAAAJEA=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        AAAAAAAAJkA=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        AAAAAAAAKEA=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        AAAAAAAAKkA=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        AAAAAAAALEA=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        AAAAAAAALkA=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        AAAAAAAAMEA=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        AAAAAAAAMUA=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        AAAAAAAAMkA=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        AAAAAAAAM0A=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        AAAAAAAANEA=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        AAAAAAAANUA=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        AAAAAAAANkA=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        AAAAAAAAN0A=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        AAAAAAAAOEA=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        AAAAAAAAOUA=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        AAAAAAAAOkA=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        AAAAAAAAO0A=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        AAAAAAAAPEA=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        AAAAAAAAPUA=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        AAAAAAAAPkA=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        AAAAAAAAP0A=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        AAAAAAAAQEA=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        AAAAAACAQEA=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        AAAAAAAAQUA=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        AAAAAACAQUA=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        AAAAAAAAQkA=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        AAAAAACAQkA=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        AAAAAAAAQ0A=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        AAAAAACAQ0A=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        AAAAAAAAREA=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        AAAAAACAREA=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        AAAAAAAARUA=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        AAAAAACARUA=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        AAAAAAAARkA=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        AAAAAACARkA=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        AAAAAAAAR0A=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        AAAAAACAR0A=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        AAAAAAAASEA=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        AAAAAACASEA=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        AAAAAAAASUA=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        AAAAAACASUA=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        AAAAAAAASkA=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        AAAAAACASkA=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        AAAAAAAAS0A=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        AAAAAACAS0A=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        AAAAAAAATEA=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        AAAAAACATEA=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        AAAAAAAATUA=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        AAAAAACATUA=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        AAAAAAAATkA=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        AAAAAACATkA=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        AAAAAAAAT0A=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        AAAAAACAT0A=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        AAAAAAAAUEA=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        AAAAAABAUEA=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        AAAAAACAUEA=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        AAAAAADAUEA=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        AAAAAAAAUUA=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        AAAAAABAUUA=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        AAAAAACAUUA=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        AAAAAADAUUA=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        AAAAAAAAUkA=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        AAAAAABAUkA=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        AAAAAACAUkA=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        AAAAAADAUkA=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        AAAAAAAAU0A=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        AAAAAABAU0A=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        AAAAAACAU0A=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        AAAAAADAU0A=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        AAAAAAAAVEA=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        AAAAAABAVEA=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        AAAAAACAVEA=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        AAAAAADAVEA=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        AAAAAAAAVUA=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        AAAAAABAVUA=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        AAAAAACAVUA=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        AAAAAADAVUA=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        AAAAAAAAVkA=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        AAAAAABAVkA=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        AAAAAACAVkA=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        AAAAAADAVkA=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        AAAAAAAAV0A=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        AAAAAABAV0A=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        AAAAAACAV0A=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        AAAAAADAV0A=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        AAAAAAAAWEA=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        AAAAAABAWEA=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        AAAAAACAWEA=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        AAAAAADAWEA=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        AAAAAAAAWUA=
    WARMUP: true
    WARMUP_EPOCH: 250
  state:
    ACT: Mish
    ACT_LIST: *id003
    BATCH_SIZE: 1
    EMB_DIM: *id004
    EPOCH: 1000
    LOSS: CosFace
    LOSSES: *id005
    LR: 0.0005
    M_RANGE: *id006
    NUM_SAMPLE: 2500
    ONLY_METRIC_LEARN: true
    SHUFFLE: true
    S_RANGE: *id007
    WARMUP: true
    WARMUP_EPOCH: 250
VIS: !!python/object/new:easydict.EasyDict
  dictitems:
    MAX_SAMPLES: 40000
    PLOT_METRIC_METHOD: cosine
    PLOT_SAVE_ROOT: ./embedding_result_img
    PLOT_VISUALIZATION: true
    TSNE_N_ITER: 1000
    TSNE_PERPLEXITY: 40
    TSNE_RANDOM_SEED: 614
  state:
    MAX_SAMPLES: 40000
    PLOT_METRIC_METHOD: cosine
    PLOT_SAVE_ROOT: ./embedding_result_img
    PLOT_VISUALIZATION: true
    TSNE_N_ITER: 1000
    TSNE_PERPLEXITY: 40
    TSNE_RANDOM_SEED: 614
WORKERS: 0
